name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/setup-java@v3
      - run: npm install -g bats
      - run: bats -v
      - name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Mvn version
        run: mvn --version
